version: '3.8'

networks: 
    dev:

services: 
  db:
      image: 'mariadb:latest'
      environment:
          MYSQL_PASSWORD: 'root'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: sf_ws
      networks:
          - dev
      volumes:
          - db_data:/var/lib/mysql
      ports:
          - '3306:3306'

volumes:
  db_data: